server:
  port: 8888

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/KOS_DB
    username: root
    password: 2536
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
