server:
  port: 8888

#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/kosdb
#    username:
#    password:
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true
